// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pollut.proto

package com.protoTest.smartcity;

public final class Pollut {
  private Pollut() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface pollutionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pollution)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 PM2_5 = 1;</code>
     */
    boolean hasPM25();
    /**
     * <code>optional int32 PM2_5 = 1;</code>
     */
    int getPM25();

    /**
     * <code>optional float NOISELEVEL = 2;</code>
     */
    boolean hasNOISELEVEL();
    /**
     * <code>optional float NOISELEVEL = 2;</code>
     */
    float getNOISELEVEL();

    /**
     * <code>optional int32 CO2 = 3;</code>
     */
    boolean hasCO2();
    /**
     * <code>optional int32 CO2 = 3;</code>
     */
    int getCO2();

    /**
     * <code>optional int32 PM10 = 4;</code>
     */
    boolean hasPM10();
    /**
     * <code>optional int32 PM10 = 4;</code>
     */
    int getPM10();
  }
  /**
   * Protobuf type {@code pollution}
   */
  public  static final class pollution extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pollution)
      pollutionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use pollution.newBuilder() to construct.
    private pollution(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private pollution() {
      pM25_ = 0;
      nOISELEVEL_ = 0F;
      cO2_ = 0;
      pM10_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private pollution(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              pM25_ = input.readInt32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              nOISELEVEL_ = input.readFloat();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              cO2_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              pM10_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protoTest.smartcity.Pollut.internal_static_pollution_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protoTest.smartcity.Pollut.internal_static_pollution_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protoTest.smartcity.Pollut.pollution.class, com.protoTest.smartcity.Pollut.pollution.Builder.class);
    }

    private int bitField0_;
    public static final int PM2_5_FIELD_NUMBER = 1;
    private int pM25_;
    /**
     * <code>optional int32 PM2_5 = 1;</code>
     */
    public boolean hasPM25() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 PM2_5 = 1;</code>
     */
    public int getPM25() {
      return pM25_;
    }

    public static final int NOISELEVEL_FIELD_NUMBER = 2;
    private float nOISELEVEL_;
    /**
     * <code>optional float NOISELEVEL = 2;</code>
     */
    public boolean hasNOISELEVEL() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional float NOISELEVEL = 2;</code>
     */
    public float getNOISELEVEL() {
      return nOISELEVEL_;
    }

    public static final int CO2_FIELD_NUMBER = 3;
    private int cO2_;
    /**
     * <code>optional int32 CO2 = 3;</code>
     */
    public boolean hasCO2() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 CO2 = 3;</code>
     */
    public int getCO2() {
      return cO2_;
    }

    public static final int PM10_FIELD_NUMBER = 4;
    private int pM10_;
    /**
     * <code>optional int32 PM10 = 4;</code>
     */
    public boolean hasPM10() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 PM10 = 4;</code>
     */
    public int getPM10() {
      return pM10_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, pM25_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, nOISELEVEL_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, cO2_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, pM10_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pM25_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, nOISELEVEL_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, cO2_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, pM10_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protoTest.smartcity.Pollut.pollution)) {
        return super.equals(obj);
      }
      com.protoTest.smartcity.Pollut.pollution other = (com.protoTest.smartcity.Pollut.pollution) obj;

      boolean result = true;
      result = result && (hasPM25() == other.hasPM25());
      if (hasPM25()) {
        result = result && (getPM25()
            == other.getPM25());
      }
      result = result && (hasNOISELEVEL() == other.hasNOISELEVEL());
      if (hasNOISELEVEL()) {
        result = result && (
            java.lang.Float.floatToIntBits(getNOISELEVEL())
            == java.lang.Float.floatToIntBits(
                other.getNOISELEVEL()));
      }
      result = result && (hasCO2() == other.hasCO2());
      if (hasCO2()) {
        result = result && (getCO2()
            == other.getCO2());
      }
      result = result && (hasPM10() == other.hasPM10());
      if (hasPM10()) {
        result = result && (getPM10()
            == other.getPM10());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasPM25()) {
        hash = (37 * hash) + PM2_5_FIELD_NUMBER;
        hash = (53 * hash) + getPM25();
      }
      if (hasNOISELEVEL()) {
        hash = (37 * hash) + NOISELEVEL_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getNOISELEVEL());
      }
      if (hasCO2()) {
        hash = (37 * hash) + CO2_FIELD_NUMBER;
        hash = (53 * hash) + getCO2();
      }
      if (hasPM10()) {
        hash = (37 * hash) + PM10_FIELD_NUMBER;
        hash = (53 * hash) + getPM10();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protoTest.smartcity.Pollut.pollution parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protoTest.smartcity.Pollut.pollution parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protoTest.smartcity.Pollut.pollution parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protoTest.smartcity.Pollut.pollution parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protoTest.smartcity.Pollut.pollution parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protoTest.smartcity.Pollut.pollution parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protoTest.smartcity.Pollut.pollution parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protoTest.smartcity.Pollut.pollution parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protoTest.smartcity.Pollut.pollution parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protoTest.smartcity.Pollut.pollution parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protoTest.smartcity.Pollut.pollution parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protoTest.smartcity.Pollut.pollution parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protoTest.smartcity.Pollut.pollution prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pollution}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pollution)
        com.protoTest.smartcity.Pollut.pollutionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protoTest.smartcity.Pollut.internal_static_pollution_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protoTest.smartcity.Pollut.internal_static_pollution_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protoTest.smartcity.Pollut.pollution.class, com.protoTest.smartcity.Pollut.pollution.Builder.class);
      }

      // Construct using com.protoTest.smartcity.Pollut.pollution.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pM25_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        nOISELEVEL_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        cO2_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        pM10_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protoTest.smartcity.Pollut.internal_static_pollution_descriptor;
      }

      public com.protoTest.smartcity.Pollut.pollution getDefaultInstanceForType() {
        return com.protoTest.smartcity.Pollut.pollution.getDefaultInstance();
      }

      public com.protoTest.smartcity.Pollut.pollution build() {
        com.protoTest.smartcity.Pollut.pollution result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protoTest.smartcity.Pollut.pollution buildPartial() {
        com.protoTest.smartcity.Pollut.pollution result = new com.protoTest.smartcity.Pollut.pollution(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.pM25_ = pM25_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.nOISELEVEL_ = nOISELEVEL_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.cO2_ = cO2_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.pM10_ = pM10_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protoTest.smartcity.Pollut.pollution) {
          return mergeFrom((com.protoTest.smartcity.Pollut.pollution)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protoTest.smartcity.Pollut.pollution other) {
        if (other == com.protoTest.smartcity.Pollut.pollution.getDefaultInstance()) return this;
        if (other.hasPM25()) {
          setPM25(other.getPM25());
        }
        if (other.hasNOISELEVEL()) {
          setNOISELEVEL(other.getNOISELEVEL());
        }
        if (other.hasCO2()) {
          setCO2(other.getCO2());
        }
        if (other.hasPM10()) {
          setPM10(other.getPM10());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protoTest.smartcity.Pollut.pollution parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protoTest.smartcity.Pollut.pollution) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int pM25_ ;
      /**
       * <code>optional int32 PM2_5 = 1;</code>
       */
      public boolean hasPM25() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 PM2_5 = 1;</code>
       */
      public int getPM25() {
        return pM25_;
      }
      /**
       * <code>optional int32 PM2_5 = 1;</code>
       */
      public Builder setPM25(int value) {
        bitField0_ |= 0x00000001;
        pM25_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 PM2_5 = 1;</code>
       */
      public Builder clearPM25() {
        bitField0_ = (bitField0_ & ~0x00000001);
        pM25_ = 0;
        onChanged();
        return this;
      }

      private float nOISELEVEL_ ;
      /**
       * <code>optional float NOISELEVEL = 2;</code>
       */
      public boolean hasNOISELEVEL() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional float NOISELEVEL = 2;</code>
       */
      public float getNOISELEVEL() {
        return nOISELEVEL_;
      }
      /**
       * <code>optional float NOISELEVEL = 2;</code>
       */
      public Builder setNOISELEVEL(float value) {
        bitField0_ |= 0x00000002;
        nOISELEVEL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float NOISELEVEL = 2;</code>
       */
      public Builder clearNOISELEVEL() {
        bitField0_ = (bitField0_ & ~0x00000002);
        nOISELEVEL_ = 0F;
        onChanged();
        return this;
      }

      private int cO2_ ;
      /**
       * <code>optional int32 CO2 = 3;</code>
       */
      public boolean hasCO2() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 CO2 = 3;</code>
       */
      public int getCO2() {
        return cO2_;
      }
      /**
       * <code>optional int32 CO2 = 3;</code>
       */
      public Builder setCO2(int value) {
        bitField0_ |= 0x00000004;
        cO2_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 CO2 = 3;</code>
       */
      public Builder clearCO2() {
        bitField0_ = (bitField0_ & ~0x00000004);
        cO2_ = 0;
        onChanged();
        return this;
      }

      private int pM10_ ;
      /**
       * <code>optional int32 PM10 = 4;</code>
       */
      public boolean hasPM10() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 PM10 = 4;</code>
       */
      public int getPM10() {
        return pM10_;
      }
      /**
       * <code>optional int32 PM10 = 4;</code>
       */
      public Builder setPM10(int value) {
        bitField0_ |= 0x00000008;
        pM10_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 PM10 = 4;</code>
       */
      public Builder clearPM10() {
        bitField0_ = (bitField0_ & ~0x00000008);
        pM10_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pollution)
    }

    // @@protoc_insertion_point(class_scope:pollution)
    private static final com.protoTest.smartcity.Pollut.pollution DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protoTest.smartcity.Pollut.pollution();
    }

    public static com.protoTest.smartcity.Pollut.pollution getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<pollution>
        PARSER = new com.google.protobuf.AbstractParser<pollution>() {
      public pollution parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new pollution(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<pollution> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<pollution> getParserForType() {
      return PARSER;
    }

    public com.protoTest.smartcity.Pollut.pollution getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pollution_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pollution_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014pollut.proto\"I\n\tpollution\022\r\n\005PM2_5\030\001 \001" +
      "(\005\022\022\n\nNOISELEVEL\030\002 \001(\002\022\013\n\003CO2\030\003 \001(\005\022\014\n\004P" +
      "M10\030\004 \001(\005B\031\n\027com.protoTest.smartcity"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_pollution_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pollution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pollution_descriptor,
        new java.lang.String[] { "PM25", "NOISELEVEL", "CO2", "PM10", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
